SET IDENTITY_INSERT [dbo].[CarModels] ON
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (1, NULL, N'Cobra', 1)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (2, NULL, N'33', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (3, NULL, N'75', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (4, NULL, N'145', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (5, NULL, N'146', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (6, NULL, N'147', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (7, NULL, N'155', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (8, NULL, N'156', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (9, NULL, N'156 Crosswagon', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (10, NULL, N'159', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (11, NULL, N'164', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (12, NULL, N'166', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (13, NULL, N'Alfetta', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (14, NULL, N'Brera', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (15, NULL, N'Giulia', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (16, NULL, N'Guilietta', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (17, NULL, N'GT', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (18, NULL, N'GTV', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (19, NULL, N'MiTo', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (20, NULL, N'Spider', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (21, NULL, N'Stelvio', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (22, NULL, N'Ostalo', 2)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (23, NULL, N'Serija 10', 3)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (24, NULL, N'Ostalo', 3)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (27, NULL, N'DB 9', 4)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (28, NULL, N'Ostalo', 4)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (29, NULL, N'80', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (30, NULL, N'90', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (31, NULL, N'100', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (32, NULL, N'200', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (33, NULL, N'A1', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (34, NULL, N'A2', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (35, NULL, N'A3', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (36, NULL, N'A4', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (37, NULL, N'A5', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (38, NULL, N'A6', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (39, NULL, N'A8', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (40, NULL, N'A6 Allroad', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (41, NULL, N'A7', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (42, NULL, N'Coupe', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (43, NULL, N'Q2', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (44, NULL, N'Q3', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (45, NULL, N'Q5', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (46, NULL, N'Q7', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (47, NULL, N'Q8', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (48, NULL, N'Quattro', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (49, NULL, N'R8', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (50, NULL, N'RS3', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (51, NULL, N'S3', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (52, NULL, N'S4', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (53, NULL, N'S5', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (54, NULL, N'S6', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (55, NULL, N'S8', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (56, NULL, N'SQ5', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (57, NULL, N'SQ7', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (58, NULL, N'TT', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (59, NULL, N'Ostalo', 5)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (60, NULL, N'Mini', 6)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (61, NULL, N'Moris Marina', 6)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (62, NULL, N'Ostalo', 6)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (63, NULL, N'Continental', 7)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (64, NULL, N'Ostalo', 7)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (65, NULL, N'114', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (66, NULL, N'116', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (67, NULL, N'118', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (68, NULL, N'120', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (69, NULL, N'123', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (70, NULL, N'125', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (71, NULL, N'216', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (72, NULL, N'218', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (73, NULL, N'220', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (74, NULL, N'315', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (75, NULL, N'316', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (76, NULL, N'318', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (77, NULL, N'320', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (78, NULL, N'323', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (79, NULL, N'325', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (80, NULL, N'328', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (81, NULL, N'330', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (82, NULL, N'335', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (83, NULL, N'Compact', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (84, NULL, N'318 GT', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (85, NULL, N'320 GT', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (86, NULL, N'418', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (87, NULL, N'420', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (88, NULL, N'428', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (89, NULL, N'430', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (90, NULL, N'435', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (91, NULL, N'518', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (92, NULL, N'520', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (93, NULL, N'523', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (94, NULL, N'524', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (95, NULL, N'525', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (96, NULL, N'528', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (97, NULL, N'530', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (98, NULL, N'535', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (99, NULL, N'540', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (100, NULL, N'545', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (101, NULL, N'520 GT', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (102, NULL, N'530 GT ', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (103, NULL, N'630', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (104, NULL, N'635', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (105, NULL, N'640', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (106, NULL, N'645', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (107, NULL, N'650', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (108, NULL, N'700', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (109, NULL, N'725', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (110, NULL, N'728', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (111, NULL, N'730', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (112, NULL, N'735', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (113, NULL, N'740', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (114, NULL, N'745', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (115, NULL, N'750', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (116, NULL, N'760', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (117, NULL, N'840', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (118, NULL, N'850', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (119, NULL, N'M1', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (120, NULL, N'M3', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (121, NULL, N'M4', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (122, NULL, N'M5', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (123, NULL, N'M6', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (124, NULL, N'X1', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (125, NULL, N'X2', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (126, NULL, N'X3', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (127, NULL, N'X4', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (128, NULL, N'X5', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (129, NULL, N'X6', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (130, NULL, N'i3', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (131, NULL, N'Z3', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (132, NULL, N'Z4', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (133, NULL, N'2002', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (134, NULL, N'Ostalo', 8)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (135, NULL, N'Regal', 9)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (136, NULL, N'Skyhawk', 78)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (137, NULL, N'Ostalo', 78)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (138, NULL, N'Deville', 9)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (139, NULL, N'Escalade', 9)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (140, NULL, N'Fleetwood', 9)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (141, NULL, N'Ostalo', 9)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (142, NULL, N'Ego', 10)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (143, NULL, N'Tengo', 10)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (144, NULL, N'Tiggo', 10)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (145, NULL, N'Ostalo', 10)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (146, NULL, N'Aveo', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (147, NULL, N'Beretta', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (148, NULL, N'Blazer', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (149, NULL, N'Camaro', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (150, NULL, N'Caprice', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (151, NULL, N'Captiva', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (152, NULL, N'Corvette', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (153, NULL, N'Cruze', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (154, NULL, N'Epica', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (155, NULL, N'Evanda', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (156, NULL, N'Impala', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (157, NULL, N'Kalos', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (158, NULL, N'Lacetti', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (159, NULL, N'Lumina', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (160, NULL, N'Malibu', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (161, NULL, N'Matiz', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (162, NULL, N'Nubira', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (163, NULL, N'Orlando', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (164, NULL, N'Spark', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (165, NULL, N'Tacuma', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (166, NULL, N'Tahoe', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (167, NULL, N'Trailblazer', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (168, NULL, N'Trans Sport', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (169, NULL, N'Trax', 11)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (170, NULL, N'300M', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (171, NULL, N'300C', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (172, NULL, N'Grand Voyager', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (173, NULL, N'GS', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (174, NULL, N'Le Baron', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (175, NULL, N'Neon', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (176, NULL, N'Pacifica', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (177, NULL, N'PT Cruser', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (178, NULL, N'Sebring', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (179, NULL, N'Stratus', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (180, NULL, N'Sunbeam', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (181, NULL, N'Town & Country', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (182, NULL, N'Voyager', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (183, NULL, N'Ostalo', 12)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (184, NULL, N'2CV', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (185, NULL, N'Ami', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (186, NULL, N'AX', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (187, NULL, N'Berlingo', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (188, NULL, N'BX', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (189, NULL, N'C-Crosser', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (190, NULL, N'C-ELYSEE', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (191, NULL, N'C1', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (192, NULL, N'C2', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (193, NULL, N'C3', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (194, NULL, N'C3 Picasso', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (195, NULL, N'C4', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (196, NULL, N'C4 Aircross', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (197, NULL, N'C4 Cactus', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (198, NULL, N'C4 Grand Picasso', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (199, NULL, N'C4 Picasso', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (200, NULL, N'C5', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (201, NULL, N'C6', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (202, NULL, N'C8', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (203, NULL, N'C15', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (204, NULL, N'CX', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (205, NULL, N'DS', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (206, NULL, N'DS3', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (207, NULL, N'DS4', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (208, NULL, N'DS5', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (209, NULL, N'Dyane', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (210, NULL, N'GS', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (211, NULL, N'GSA', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (212, NULL, N'Jumpy', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (213, NULL, N'Nemo', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (214, NULL, N'Saxo', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (215, NULL, N'Visa', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (216, NULL, N'Xantia', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (217, NULL, N'XM', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (218, NULL, N'Xsara', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (219, NULL, N'Xsara Picasso', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (220, NULL, N'ZX', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (221, NULL, N'Ostalo ', 13)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (222, NULL, N'Aro', -1)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (223, NULL, N'Dokker', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (224, NULL, N'Double', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (225, NULL, N'Duster', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (226, NULL, N'Lodgy', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (227, NULL, N'Logan', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (228, NULL, N'Nova', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (229, NULL, N'Pickup', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (230, NULL, N'Sandero', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (231, NULL, N'Solenza', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (232, NULL, N'Stepway', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (233, NULL, N'Super Nova', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (234, NULL, N'Ostalo', 14)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (235, NULL, N'Espero', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (236, NULL, N'Kalos', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (237, NULL, N'Korando', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (238, NULL, N'Lacetti', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (239, NULL, N'Lanos', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (240, NULL, N'Leganza', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (241, NULL, N'Matiz', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (242, NULL, N'Musso', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (243, NULL, N'Nexia', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (244, NULL, N'Nubira', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (245, NULL, N'Rezzo', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (246, NULL, N'Tacuma', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (247, NULL, N'Tica', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (248, NULL, N'Ostalo', 15)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (249, NULL, N'Applause', 16)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (250, NULL, N'Charade', 16)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (251, NULL, N'Cuore', 16)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (252, NULL, N'Feroza', 16)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (253, NULL, N'Mateira', 16)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (254, NULL, N'Move', 16)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (255, NULL, N'Rocky', 16)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (256, NULL, N'Sirion', 16)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (257, NULL, N'Terios', 16)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (258, NULL, N'YRV', 16)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (259, NULL, N'Ostalo', 16)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (260, NULL, N'Avenger', 17)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (261, NULL, N'Caliber', 17)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (262, NULL, N'Interpid', 17)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (263, NULL, N'Journey', 17)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (264, NULL, N'Neon', 17)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (265, NULL, N'Nitro', 17)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (266, NULL, N'RAM', 17)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (267, NULL, N'Stealth', 17)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (268, NULL, N'Ostalo', 17)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (269, NULL, N'D5', 18)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (270, NULL, N'Ostalo', 18)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (271, NULL, N'599', 19)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (272, NULL, N'Ostalo', 19)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (273, NULL, N'125', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (274, NULL, N'126', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (275, NULL, N'127', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (276, NULL, N'131', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (277, NULL, N'500', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (278, NULL, N'500C', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (279, NULL, N'500L', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (280, NULL, N'500X', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (281, NULL, N'600', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (282, NULL, N'850', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (283, NULL, N'1100', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (284, NULL, N'1107', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (285, NULL, N'1300', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (286, NULL, N'Albea', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (287, NULL, N'Berchetta', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (288, NULL, N'Brava', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (289, NULL, N'Bravo', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (290, NULL, N'Campagnola', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (291, NULL, N'Cinquecento', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (292, NULL, N'Coupe', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (293, NULL, N'Croma', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (294, NULL, N'Doblo', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (295, NULL, N'EVO', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (296, NULL, N'Fiorino', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (297, NULL, N'Freemont', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (298, NULL, N'Grande Punto', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (299, NULL, N'Idea', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (300, NULL, N'Linea', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (301, NULL, N'Marea', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (302, NULL, N'Marengo', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (303, NULL, N'Multipla', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (304, NULL, N'Palio', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (305, NULL, N'Panda', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (306, NULL, N'Punto', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (307, NULL, N'Qubo', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (308, NULL, N'Scudo', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (309, NULL, N'Sedici', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (310, NULL, N'Seicento', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (311, NULL, N'Spider Europa', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (312, NULL, N'Stilo', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (313, NULL, N'Tempra', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (314, NULL, N'Tipo', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (315, NULL, N'Ulysse', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (316, NULL, N'Uno', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (317, NULL, N'x 1/9', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (318, NULL, N'Ostalo', 21)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (319, NULL, N'Aerostar', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (320, NULL, N'B-Max', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (321, NULL, N'C-Max', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (322, NULL, N'Cougar', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (323, NULL, N'Courier', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (324, NULL, N'Eco Sport', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (325, NULL, N'Edge', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (326, NULL, N'Escort', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (327, NULL, N'Excursion', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (328, NULL, N'Expedition', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (329, NULL, N'Explorer', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (330, NULL, N'F 150', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (331, NULL, N'Fiesta', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (332, NULL, N'Focus', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (333, NULL, N'Fusion', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (334, NULL, N'Galaxy', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (335, NULL, N'Granada', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (336, NULL, N'Grand C- Max', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (337, NULL, N'Ka', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (338, NULL, N'Kuga', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (339, NULL, N'Maverick', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (340, NULL, N'Mondeo', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (341, NULL, N'Mustang', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (342, NULL, N'Orion', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (343, NULL, N'Probe', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (344, NULL, N'Puma', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (345, NULL, N'Ranger', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (346, NULL, N'S-Max', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (347, NULL, N'Scorpio', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (348, NULL, N'Sierra', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (349, NULL, N'Street Ka', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (350, NULL, N'Taunus', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (351, NULL, N'Taurus', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (352, NULL, N'Torneo', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (353, NULL, N'Torneo Connect', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (354, NULL, N'Torneo Courier', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (355, NULL, N'Ostalo', 22)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (356, NULL, N'3102', 23)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (357, NULL, N'Ostalo', 23)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (358, NULL, N'H6', 24)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (359, NULL, N'Steed', 24)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (360, NULL, N'Steed 5', 24)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (361, NULL, N'Ostalo', 24)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (362, NULL, N'Yukon', 25)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (363, NULL, N'Ostalo', 25)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (364, NULL, N'Accord', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (365, NULL, N'Civic', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (366, NULL, N'Concerto', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (367, NULL, N'CR-V', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (368, NULL, N'CR-Z', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (369, NULL, N'CRX', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (370, NULL, N'FR-V', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (371, NULL, N'HR-V', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (372, NULL, N'Insight', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (373, NULL, N'Jazz', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (374, NULL, N'Legend', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (375, NULL, N'Prelude', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (376, NULL, N'Stream', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (377, NULL, N'Ostalo', 26)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (378, NULL, N'H3', 27)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (379, NULL, N'H2', 27)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (380, NULL, N'H1', 27)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (381, NULL, N'Ostalo', 27)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (382, NULL, N'Accent', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (383, NULL, N'Atos', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (384, NULL, N'Coupe', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (385, NULL, N'Elantra', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (386, NULL, N'Galloper', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (387, NULL, N'Genesis', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (388, NULL, N'Getz', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (389, NULL, N'H 1', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (390, NULL, N'H 100', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (391, NULL, N'i10', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (392, NULL, N'i20', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (393, NULL, N'i30', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (394, NULL, N'i40', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (395, NULL, N'Ioniq', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (396, NULL, N'ix20', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (397, NULL, N'ix35', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (398, NULL, N'ix55', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (399, NULL, N'Kona', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (400, NULL, N'Lantra', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (401, NULL, N'Matrix', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (402, NULL, N'Pony', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (403, NULL, N'S-Coupe', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (404, NULL, N'Santa Fe', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (405, NULL, N'Santamo', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (406, NULL, N'Sonata', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (407, NULL, N'Sonica', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (408, NULL, N'Terracan', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (409, NULL, N'Trajet', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (410, NULL, N'Tuscon', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (411, NULL, N'Veloster', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (412, NULL, N'Ostalo', 28)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (413, NULL, N'FX30', 29)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (414, NULL, N'FX35', 29)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (415, NULL, N'FX45', 29)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (416, NULL, N'Q30', 29)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (417, NULL, N'Q70', 29)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (418, NULL, N'Ostalo', 29)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (419, NULL, N'D-Max', 30)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (420, NULL, N'Trooper', 30)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (421, NULL, N'Ostalo', 30)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (422, NULL, N'E-Pace', 31)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (423, NULL, N'F-Pace', 31)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (424, NULL, N'S-Type', 31)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (425, NULL, N'X-Type', 31)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (426, NULL, N'XE', 31)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (427, NULL, N'XF', 31)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (428, NULL, N'XJ', 31)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (429, NULL, N'XJ6', 31)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (430, NULL, N'XJ12', 31)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (431, NULL, N'XK', 31)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (432, NULL, N'Ostalo', 31)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (433, NULL, N'Chreokee', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (434, NULL, N'CJ', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (435, NULL, N'Commander', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (436, NULL, N'Compass', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (437, NULL, N'Grand Cherokee', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (438, NULL, N'Liberty', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (439, NULL, N'Patriot', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (440, NULL, N'Renegade', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (441, NULL, N'Wagoneer', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (442, NULL, N'Willys', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (443, NULL, N'Wrangler', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (444, NULL, N'Ostalo', 32)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (445, NULL, N'Carens', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (446, NULL, N'Carnival', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (447, NULL, N'cee ` d', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (448, NULL, N'cee ` sw', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (449, NULL, N'Cerato', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (450, NULL, N'Clarus', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (451, NULL, N'Joice', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (452, NULL, N'Magentis', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (453, NULL, N'Picanto', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (454, NULL, N'Pride', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (455, NULL, N'pro_cee ` d', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (456, NULL, N'Rio', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (457, NULL, N'Sephia', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (458, NULL, N'Shuma', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (459, NULL, N'Sorento', 33)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (460, NULL, N'110', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (461, NULL, N'111', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (462, NULL, N'112', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (463, NULL, N'1200', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (464, NULL, N'1300', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (465, NULL, N'1500', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (466, NULL, N'1600', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (467, NULL, N'2103', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (468, NULL, N'2104', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (469, NULL, N'2107', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (470, NULL, N'Aleko', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (471, NULL, N'Kalina', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (472, NULL, N'Niva', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (473, NULL, N'Riva', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (474, NULL, N'Samara', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (475, NULL, N'Vesta', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (476, NULL, N'Ostalo', 34)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (477, NULL, N'Gallardo', 35)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (478, NULL, N'Ostalo', 35)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (479, NULL, N'Beta', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (480, NULL, N'Dedra', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (481, NULL, N'Delta', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (482, NULL, N'Kappa', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (483, NULL, N'Lybra', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (484, NULL, N'Musa', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (485, NULL, N'Phedra', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (486, NULL, N'Prisma', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (487, NULL, N'Thema', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (488, NULL, N'Thesis', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (489, NULL, N'Voyager', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (490, NULL, N'Ypsilon', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (491, NULL, N'Zeta', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (492, NULL, N'Ostalo', 36)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (493, NULL, N'Defender', 37)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (494, NULL, N'Discovery', 37)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (495, NULL, N'Freelander', 37)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (496, NULL, N'Range Rover', 37)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (497, NULL, N'Range Rover Evoque', 37)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (498, NULL, N'Range Rover Sport ', 37)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (499, NULL, N'Range Rover Velar', 37)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (500, NULL, N'Range Rover Vogue', 37)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (501, NULL, N'Serija II', 37)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (502, NULL, N'Ostalo', 37)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (503, NULL, N'GS', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (504, NULL, N'GS 300', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (505, NULL, N'GS 450', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (506, NULL, N'IS', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (507, NULL, N'IS 200', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (508, NULL, N'IS 220 ', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (509, NULL, N'LS', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (510, NULL, N'LS 460', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (511, NULL, N'RX', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (512, NULL, N'RX 300', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (513, NULL, N'RX 450', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (514, NULL, N'Ostalo', 38)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (515, NULL, N'Navigator', 39)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (516, NULL, N'Town car', 39)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (517, NULL, N'Ostalo', 39)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (518, NULL, N'Bolero', 40)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (519, NULL, N'CJ', 40)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (520, NULL, N'Goa', 40)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (521, NULL, N'Ostalo', 40)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (522, NULL, N'Ghibli', 41)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (523, NULL, N'Granturismo', 41)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (524, NULL, N'Levante', 41)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (525, NULL, N'Quattroporte', 41)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (526, NULL, N'Ostalo', 41)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (527, NULL, N'2', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (528, NULL, N'3', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (529, NULL, N'5', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (530, NULL, N'6', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (531, NULL, N'121', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (532, NULL, N'323', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (533, NULL, N'626', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (534, NULL, N'929', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (535, NULL, N'B 250', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (536, NULL, N'CX-3', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (537, NULL, N'CX-5', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (538, NULL, N'CX-7', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (539, NULL, N'Demio', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (540, NULL, N'MPV', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (541, NULL, N'MX-3', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (542, NULL, N'MX-5', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (543, NULL, N'Premacy', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (544, NULL, N'Protege', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (545, NULL, N'RX-8', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (546, NULL, N'Tribute', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (547, NULL, N'Xedos', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (548, NULL, N'Ostalo', 42)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (549, NULL, N'A 140', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (550, NULL, N'A 150', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (551, NULL, N'A 160', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (552, NULL, N'A 170', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (553, NULL, N'A 180', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (554, NULL, N'A 190', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (555, NULL, N'A 200', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (556, NULL, N'A 210', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (557, NULL, N'A 220', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (558, NULL, N'A 250', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (559, NULL, N'A 45 AMG', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (560, NULL, N'B 150', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (561, NULL, N'B 160', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (562, NULL, N'B 170', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (563, NULL, N'B 180', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (564, NULL, N'B 200', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (565, NULL, N'C 180', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (566, NULL, N'C 200', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (567, NULL, N'C 220', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (568, NULL, N'C 230', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (569, NULL, N'C 240', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (570, NULL, N'C 250', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (571, NULL, N'C 270', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (572, NULL, N'C 280', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (573, NULL, N'C 300 ', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (574, NULL, N'C 320', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (575, NULL, N'C 63 AMG', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (576, NULL, N'CE 200', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (577, NULL, N'CE 220', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (578, NULL, N'CE 230', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (579, NULL, N'CE 300', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (580, NULL, N'CLA 180', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (581, NULL, N'CLA 200', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (582, NULL, N'CLA 220', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (583, NULL, N'CL 500', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (584, NULL, N'CL 63 AMG', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (585, NULL, N'CLC 220', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (586, NULL, N'CLK 200', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (587, NULL, N'CLK 220', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (588, NULL, N'CLK 230', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (589, NULL, N'CLG 240', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (590, NULL, N'CLK 270', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (591, NULL, N'CLK 320', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (592, NULL, N'CLK 500', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (593, NULL, N'CLS 220', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (594, NULL, N'CLS 250', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (595, NULL, N'CLS 320', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (596, NULL, N'CLS 350', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (597, NULL, N'CLS 500', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (598, NULL, N'CLS 55 AMG', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (599, NULL, N'E 200', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (600, NULL, N'E 220', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (601, NULL, N'E 230', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (602, NULL, N'E 240', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (603, NULL, N'E 250', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (604, NULL, N'E 260', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (605, NULL, N'E 270', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (606, NULL, N'E 280', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (607, NULL, N'E 290', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (608, NULL, N'E 300', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (609, NULL, N'E 320', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (610, NULL, N'E 350', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (611, NULL, N'E 400', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (612, NULL, N'E 43 AMG', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (613, NULL, N'E 500', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (614, NULL, N'G 230', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (615, NULL, N'G 240', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (616, NULL, N'G 250', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (617, NULL, N'G 290', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (618, NULL, N'G 300', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (619, NULL, N'G 350', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (620, NULL, N'G 400', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (621, NULL, N'G 500', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (622, NULL, N'GL 320', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (623, NULL, N'GL 350', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (624, NULL, N'GL 420', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (625, NULL, N'GL 500', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (626, NULL, N'GLA 45 AMG', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (627, NULL, N'GLA 180', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (628, NULL, N'GLA 200', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (629, NULL, N'GLA 220', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (630, NULL, N'GLC 220', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (631, NULL, N'GLC 250', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (632, NULL, N'GLE 250', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (633, NULL, N'GLE 300', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (634, NULL, N'GLE 350', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (635, NULL, N'GLK 200', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (636, NULL, N'GLK 220', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (637, NULL, N'GLK 250', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (638, NULL, N'GLK 320', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (639, NULL, N'GLK 350', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (640, NULL, N'GLS 500', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (641, NULL, N'GLS 350 D', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (642, NULL, N'MB 100', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (643, NULL, N'ML 230', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (644, NULL, N'ML 250', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (645, NULL, N'ML 270', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (646, NULL, N'ML 280', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (647, NULL, N'ML 320', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (648, NULL, N'ML 350', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (649, NULL, N'ML 400', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (650, NULL, N'ML 420', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (651, NULL, N'ML 430', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (652, NULL, N'ML 500', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (653, NULL, N'ML 55 AMG', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (654, NULL, N'ML 63 AMG', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (655, NULL, N'R 280', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (656, NULL, N'R 320', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (657, NULL, N'R 350', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (658, NULL, N'S 250', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (659, NULL, N'S 260', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (660, NULL, N'S 280', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (661, NULL, N'S 300', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (662, NULL, N'S 320', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (663, NULL, N'S 350', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (664, NULL, N'S 400', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (665, NULL, N'S 500', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (666, NULL, N'S 550', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (667, NULL, N'S 63 AMG', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (668, NULL, N'SL 300', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (669, NULL, N'SL 350', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (670, NULL, N'SL 500', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (671, NULL, N'SLK 200', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (672, NULL, N'SLK 230', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (673, NULL, N'Vaneo', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (674, NULL, N'190', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (675, NULL, N'Ostalo', 43)
INSERT INTO [dbo].[CarModels] ([Id], [Code], [Title], [CarTypeId]) VALUES (676, NULL, N'355', 19)
SET IDENTITY_INSERT [dbo].[CarModels] OFF
